repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8 # Use a specific version for stability
    hooks:
    -   id: clang-format
        types_or: [c, c++]
        args: ['-i'] # The '-i' flag formats files in-place