#!/bin/bash
# This file is auto-generated by the GraphyFlow backend.

# --- *** 关键修正：使其能够处理不同的目标 *** ---
TARGET=$1
EXECUTABLE="{{EXECUTABLE_NAME}}"
KERNEL="{{KERNEL_NAME}}"

# 默认目标为 sw_emu
if [ -z "$TARGET" ]; then
    TARGET="sw_emu"
fi

echo "--- Running for target: $TARGET ---"

# 1. 设置环境变量
source /home/feiyang/set_env.sh

if [ "$TARGET" = "sw_emu" ] || [ "$TARGET" = "hw_emu" ]; then
    export XCL_EMULATION_MODE=$TARGET
    echo "XCL_EMULATION_MODE set to: $XCL_EMULATION_MODE"
else
    # 对于 'hw'，取消设置 XCL_EMULATION_MODE
    unset XCL_EMULATION_MODE
    echo "Running on hardware, XCL_EMULATION_MODE is unset."
fi

# 确保 LD_PRELOAD 仍然生效
export LD_PRELOAD=/lib/x86_64-linux-gnu/libOpenCL.so.1

# 2. 动态构建 .xclbin 文件路径
XCLBIN_FILE="./xclbin/${KERNEL}.${TARGET}.xclbin"
if [ ! -f "$XCLBIN_FILE" ]; then
    echo "Error: XCLBIN file not found at '$XCLBIN_FILE'"
    echo "Please make sure the project is built for the target '$TARGET' by running 'make all TARGET=$TARGET'"
    exit 1
fi

# 3. 运行 host 程序
DATASET="./graph.txt"
./${EXECUTABLE} ${XCLBIN_FILE} $DATASET
